codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "50...100"

flags:
  daily-tests-unit:
    carryforward: true
  ocp-stream-generator-unit:
    carryforward: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
