FROM quay.io/fedora/fedora:42

ENV WORK_DIR="/var/tmp" \
    DOWNSTREAM_TMT_REPO="https://gitlab.cee.redhat.com/platform-eng-core-services/sclorg-tmt-plans" \
    VERSION="42" \
    DOWNSTREAM_TMT_DIR="sclorg-tmt-plans" \
    UPSTREAM_TMT_REPO="https://github.com/sclorg/sclorg-testing-farm" \
    UPSTREAM_TMT_DIR="sclorg-testing-farm"

RUN mkdir -p ${WORK_DIR} && \
    dnf install -y python3.13-pip git && \
    git config --global http.sslVerify false && \
    git clone "${DOWNSTREAM_TMT_REPO}" "${WORK_DIR}/${DOWNSTREAM_TMT_DIR}" && \
    git clone "${UPSTREAM_TMT_REPO}" "${WORK_DIR}/${UPSTREAM_TMT_DIR}"

# Add qa-tools repos that contain 1minutetip and QA tools
RUN curl -o /etc/yum.repos.d/lpol-qa-tools.repo https://copr.devel.redhat.com/coprs/lpol/qa-tools/repo/fedora-${VERSION}/lpol-qa-tools-fedora-${VERSION}.repo && \
    dnf copr -y enable copr.devel.redhat.com/lpol/qa-tools && \
    dnf install -y python3.13-pip git tmt beaker-redhat qa-tools-workstation tmt-redhat-provision-minute tmt-provision-virtual && \
    dnf clean all

COPY . /ci-scripts

WORKDIR /ci-scripts

RUN pip install -r requirements.txt

CMD ["/ci-scripts/run_nightly_tests.sh"]
