FROM quay.io/fedora/fedora:42

ENV SHARED_DIR="/var/ci-scripts" \
    VERSION="42" \
    RELEASE_UPSTREAM="0.8.6" \
    UPSTREAM_TMT_REPO="https://github.com/sclorg/sclorg-testing-farm" \
    UPSTREAM_TMT_DIR="sclorg-testing-farm" \
    HOME="/home/nightly" \
    SUMMARY="Daily tests for SCL org projects" \
    DESCRIPTION="This image is used to run daily tests for SCL org projects in CI." \
    NAME="nightly" \
    WORK_DIR="/home/nightly/ci-scripts"

LABEL summary="${SUMMARY}" \
      description="${DESCRIPTION}" \
      io.k8s.description="${DESCRIPTION}" \
      io.k8s.display-name="SCL org Daily Tests" \
      io.k8s.vendor="SCL org" \
      architecture="x86_64"

RUN dnf install -y python3.13-pip git nss_wrapper && \
    dnf clean all

COPY requirements.sh requirements.txt "${WORK_DIR}"
RUN bash "${WORK_DIR}/requirements.sh" && pip3 install -r "${WORK_DIR}/requirements.txt" && \
    pip3 install pbincli


COPY . /root/ci-scripts
WORKDIR "${HOME}"

# USER 900

CMD ["/root/ci-scripts/run_nightly_tests.sh"]
