#!/usr/bin/env python3
import os
import sys

from pathlib import Path

DAILY_REPORTS_DIR = Path("/var/ci-scripts/daily_reports_dir/")
DAILY_SCL_TESTS_DIR = Path("/var/ci-scripts/daily_scl_tests/")

TEST_CASES = {
    # Format is test for OS and king of test, what TMT Plan is used and MSG to mail
    ("c10s", "nightly-container-c10s"),
    ("fedora", "nightly-container-fedora"),
    ("c9s", "nightly-container-c9s"),
    ("rhel8", "nightly-container-rhel8"),
    ("rhel9", "nightly-container-rhel9"),
    ("rhel10", "nightly-container-rhel10"),
}


class PVCWatcherReport:
    def __init__(self):
        self.cwd = os.getcwd()

    def iter_results_in_directory(self):
        success_tmt_plans = []
        failed_tmt_plans = []
        running_tmt_plans = []
        failed_container_tests = []
        print("Show status of all TMT/FMF plans:")
        for item in DAILY_SCL_TESTS_DIR.iterdir():
            if item.is_dir():
                if (item / "tmt_running").exists():
                    running_tmt_plans.append(item.name)
        for item in DAILY_REPORTS_DIR.iterdir():
            if item.is_dir():
                if (item / "tmt_success").exists():
                    success_tmt_plans.append(item.name)
                else:
                    failed_tmt_plans.append(item.name)
        for item in DAILY_REPORTS_DIR.iterdir():
            if item.is_dir():
                failed_container_tests.extend(
                    self.return_failed_tests(DAILY_REPORTS_DIR, item)
                )
        if running_tmt_plans:
            print("Running TMT plans that are not finished yet:")
            print("\n".join(running_tmt_plans))
        if success_tmt_plans:
            print(f"Success TMT plans in {DAILY_REPORTS_DIR} are:")
            print("\n".join(success_tmt_plans))
        if failed_tmt_plans:
            print(f"Failed TMT plans in {DAILY_REPORTS_DIR} are:")
            print("\n".join(failed_tmt_plans))
        if failed_container_tests:
            print(f"!!!!Failed container tests are: {failed_container_tests}!!!!")

    def return_failed_tests(self, directory, item) -> list:
        plan_name = "".join([x[1] for x in TEST_CASES if item.name.startswith(x[0])])
        dir_path = directory / f"{item.name}/plans/{plan_name}/data/results"
        print(f"Looking for failed tests in directory: {dir_path}")
        return list(dir_path.rglob("*.log"))

    def iter_over_executed_tests(self):
        """View all executed tests in the given directory."""
        for item in DAILY_SCL_TESTS_DIR.iterdir():
            print(f"Inspecting item in 'daily_scl_tests' directory: {item}")
            failed_container_tests = self.return_failed_tests(DAILY_SCL_TESTS_DIR, item)
            if not failed_container_tests:
                continue
            print(f"!!!!Failed container tests are: {failed_container_tests}!!!!")

    def print_report(self):
        print(
            f"Summary of Daily SCL Tests Reports generated by tests in {DAILY_SCL_TESTS_DIR}:"
        )
        self.iter_over_executed_tests()
        print(f"Summary of results reports directory {DAILY_REPORTS_DIR}:")
        self.iter_results_in_directory()


if __name__ == "__main__":
    dgr = PVCWatcherReport()
    dgr.print_report()
    sys.exit(0)
