[tox]
envlist = daily_tests, ocp-stream-generator

[testenv:daily_tests]
changedir = daily_tests
commands = python3 -m pytest -m "not integration" --color=yes -v --cov=. --cov-report=xml:coverage.xml
deps =
    pytest
    pytest-cov
    PyYAML
    requests
    xmltodict

[testenv:ocp-stream-generator]
changedir = ocp-stream-generator
commands = python3 -m pytest --color=yes -v --cov=ocp_stream_generator --cov-report=xml:coverage.xml
deps =
    pytest
    pytest-cov
    PyYAML
