---
apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    component: nightly-builds
  name: nightly-builds-pod
objects:
- apiVersion: batch/v2alpha1
  kind: CronJob
  metadata:
    name: nightly-builds-cronjob
  spec:
    schedule: "0 1 * * 1-5"  # At 01:00 on every day-of-week from Monday through Friday.
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              parent: "cronjobnightlybuilds"
          spec:
            containers:
            - name: nightly-builds-pod-fedora-test-s2i
              image: "quay.io/sclorg/daily-tests:latest"
              command: ["/ci-scripts/run_nightly_tests.sh"]
              restartPolicy: OnFailure
              env:
              - name: TARGET
                value: "fedora"
              - name: TESTS
                value: "test"
              - name: SET_TEST
                value: "S2I"
              volumeMounts:
              - mountPath: /var/tmp/daily_scl_tests
                name: nightly-builds-daily-logs
              - mountPath: /var/tmp/daily_reports_dir
                name: nightly-builds-results-logs
            volumes:
            - name: nightly-builds-daily-logs
              persistentVolumeClaim:
                claimName: claim.nighly-builds-daily-logs
            - name: nightly-builds-results-logs
              persistentVolumeClaim:
                claimName: claim.nighly-builds-results-logs
