---
- name: Bots deployment
  hosts: localhost
  vars:
    deployment: "{{ lookup('env', 'DEPLOYMENT') }}"
  tasks:
    - name: include variables
      include_vars: ../vars/{{ deployment }}.yml

    # - name: Deploy templates (need to be processed)
    #   k8s:
    #     namespace: "{{ project }}"
    #     definition: "{{ item }}"
    #     host: "{{ host }}"
    #     api_key: "{{ api_key }}"
    #     validate_certs: "{{ validate_certs }}"
    #   loop:
    #     - "{{ lookup('template', '../secret-testing-farm-api-keys.yml.j2') | from_yaml }}"

    - name: Deploy resource configs (no need to process them)
      k8s:
        namespace: "{{ project }}"
        src: "{{ item }}"
        host: "{{ host }}"
        api_key: "{{ api_key }}"
        validate_certs: "{{ validate_certs }}"
      loop:
        - ../imagestream-nightly-builds.yml
        - ../pvc-daily-logs.yml
        - ../pvc-results-logs.yml
        - ../deployment.yml

    - name: Deploy cronjobs for nightly builds
      k8s:
        namespace: "{{ project }}"
        src: "{{ item }}"
        host: "{{ host }}"
        api_key: "{{ api_key }}"
        validate_certs: "{{ validate_certs }}"
      loop:
        - "./cronjob-nightly-builds.yml"
