---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: nightly-builds
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        # populate from quay.io/sclorg/cwt
        name: quay.io/sclorg/nighly-builds
      importPolicy:
        # periodically query registry to synchronize tag and image metadata
        scheduled: true
  lookupPolicy:
    local: true
